version: '3.8'

services:
  db:
    image: postgres:13
    container_name: nest-docker-db
    environment:
      POSTGRES_USER: nestpostgres
      POSTGRES_PASSWORD: postgresnest
      POSTGRES_DB: recipebookapi
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-app
    environment:
      DB_NAME: recipebookapi
      DB_USERNAME: nestpostgres
      DB_PASSWORD: postgresnest
      DB_HOST: db
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  db-data:
